# Generated by Django 5.0.7 on 2024-07-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("search_count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Search history",
            },
        ),
    ]
